#Vagrant config to set up one virtualbox with ubuntu/xenial64 image

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.100.100"
  config.vm.network :forwarded_port, guest: 80, host:4567
  config.vm.hostname = 'docker-app'
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end
